language: python
python:
  - "2.5"
  - "2.6"
  - "2.7"

# command to install dependencies
install:
  - "pip install -r requirements.txt --use-mirrors"
  - "python setup.py -q install"
# command to run tests
script: nosetests tests
