#!/bin/sh

if [ -f "/etc/default/pystatd" ]; then
	mv /etc/default/pystatd /etc/default/pystatsd
fi

if [ -f "/etc/init/pystatd.conf" ]; then
	stop pystatd || true
	cp /usr/share/doc/python-statsd/pystatsd.conf.upstart /etc/init/pystatsd.conf
	start pystatsd || true
fi

#DEBHELPER#
